dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install nbfancy
 # - pip install -r requirements.txt

script:
  - nbfancy configure -y all_magic
 #  - nbfancy rerun
 #  - nbfancy rerun --output_dir=worksheet worksheet
  - nbfancy render
  - nbfancy render --output_dir=fancyws worksheet
  - nbfancy html
  - nbfancy html --output_dir=html/worksheet fancyws
  #- cp html/worksheet/01_r_worksheet.html html/index.html
  #- cp html/worksheet/02_placeholder_solutions.html html/01_r_worksheet-soln.html

deploy:
  provider: pages
  repo: JDBetteridge/samba_induction_r
  target-branch: gh-pages
  local-dir: html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
    python: 3.7
